branch-defaults:
  master:
    environment: appbuilder-server-dev
global:
  application_name: appbuilder-server
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-1
  profile: appbuilder
  sc: git
